# server-ip: 0.0.0.0
# server-port: 8044

rule-transforms:
  - pattern: "\\.list$"
    replace: ""

upstreams:
  - type: url
    template: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/{rule}/{rule}.list"
    # cache: 30m
    # proxy: http://127.0.0.1:7897
    # remove-comments: true
    # timeout-ms: 5000
    # headers:
    #   - "User-Agent: mrrp"
    #   - "Accept: text/plain"

  - type: file
    template: "./rules/{rule}.list"
    # cache: 30m
    # remove-comments: true
